# Generated by Django 3.0.7 on 2020-06-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='', max_length=70),
        ),
    ]
